#!/bin/bash

################################################################################################################
#                                                                                                              #
# ANONYMOUS-DNS: Simple Tool for making DNS Anonymous via Firewall & Tor daemon (can resolve .onion).          #
# CODED BY: archnon@protonmail.com                                                                             #
#                                                                                                              #
################################################################################################################
####################################################################
# Copyright (c) 2026 archnon@protonmail.com. All Rights Reserved.  #
####################################################################

##### Colors #####

RED="\e[1;31m"

GREEN="\e[1;32m"

BLUE="\e[1;34m"

P="\e[1;35m"

YELLOW="\e[1;33m"

ORANGE="\e[38;5;214m"

WHITE="\e[1;37m"

LB="\e[36m"

NC="\e[0m"

##### Default Socks5 Address #####
ADDR=127.0.0.1
PORT=9150

usage() {
  echo -e "\n${RED}[${YELLOW}warn${RED}]${ORANGE} usage: ${P}neptune ${NC}<${GREEN}COMMAND${NC}> <${LB}OPTIONS${NC}>${NC}"
  echo -e "\n${BLUE}[${YELLOW}1${BLUE}]${ORANGE} -u ${NC}<${P}url${NC}>: ${WHITE}resolv url${NC}"
  echo -e "\n${BLUE}[${YELLOW}2${BLUE}]${ORANGE} -a ${NC}<${P}addr${NC}> <${P}url${NC}>: ${WHITE}resolv url using address${NC}"
  echo -e "\n${BLUE}[${YELLOW}3${BLUE}]${ORANGE} -s ${NC}<${P}addr${NC}>: ${WHITE}set dns config to address${NC}"
}

need=e2fsprogs

if ! command -v chattr >/dev/null 2>&1; then
  if [[ $(command -v apt) ]]; then
    if ! apt install -y $need; then
      echo -e "\n${RED}[${WHITE}X${RED}] Could not install: ${ORANGE}$need${NC}"
      exit 1
    fi
  elif [[ $(command -v pacman) ]]; then
    if ! pacman -Sy --noconfirm --needed --overwrite "*" $need; then
      echo -e "\n${RED}[${WHITE}X${RED}] Could not install: ${ORANGE}$need${NC}"
      exit 1
    fi
  elif [[ $(command -v dnf) ]]; then
    if ! dnf install -y --allowerasing $need; then
      echo -e "\n${RED}[${WHITE}X${RED}] Could not install: ${ORANGE}$need${NC}"
      exit 1
    fi
  elif [[ $(command -v yum) ]]; then
    if ! yum install -y $need; then
      echo -e "\n${RED}[${WHITE}X${RED}] Could not install: ${ORANGE}$need${NC}"
      exit 1
    fi
  elif [[ $(command -v xbps-install) ]]; then
    if ! xbps-install -Sy -f -y "*" $need; then
      echo -e "\n${RED}[${WHITE}X${RED}] Could not install: ${ORANGE}$need${NC}"
      exit 1
    fi
  elif [[ $(command -v zypper) ]]; then
    if ! zypper install $need; then
      echo -e "\n${RED}[${WHITE}X${RED}] Could not install: ${ORANGE}$need${NC}"
      exit 1
    fi
  elif [[ $(command -v apk) ]]; then
    if ! apk add --no-cache $need; then
      echo -e "\n${RED}[${WHITE}X${RED}] Could not install: ${ORANGE}$need${NC}"
      exit 1
    fi
  elif [[ $(command -v emerge) ]]; then
    if ! emerge -v --oneshot --keep-going $need; then
      echo -e "\n${RED}[${WHITE}X${RED}] Could not install: ${ORANGE}$need${NC}"
      exit 1
    fi
  else
    echo -e "\n${RED}[${WHITE}X${RED}] Unsuported package manager, install: ${ORANGE}'$need'${NC}"
    exit 1
  fi
fi

echo -e "${BLUE}                                            ";
echo -e "${BLUE}                                            ";
echo -e "${BLUE}▄▄  ▄▄ ▄▄▄▄▄ ▄▄▄▄ ▄▄▄▄▄▄ ▄▄ ▄▄ ▄▄  ▄▄ ▄▄▄▄▄ ";
echo -e "${BLUE}███▄██ ██▄▄  ██▄█▀  ██   ██ ██ ███▄██ ██▄▄  ";
echo -e "${BLUE}██ ▀██ ██▄▄▄ ██     ██   ▀███▀ ██ ▀██ ██▄▄▄ ";
echo -e "${BLUE}                                            ";

echo -e "\e[95m ╔════════════════════════╗
 ║ \e[97mTool for Anonymous DNS\e[95m ║
 ╚════════════════════════╝\e[0m"
echo -e "\e[97m ᴅᴇᴠᴇʟᴏᴘᴇᴅ ʙʏ: \e[95m@strxint\e[0m"

while [ $# -gt 0 ]; do
  case $1 in
-u)
    mode=1
    url=$2

    if [ -z $url ]; then
      echo -e "\n${RED}[${WHITE}X${RED}] Missing an url${NC}"
      echo -e "\n${RED}[${YELLOW}warn${RED}]${ORANGE} usage: ${LB}neptune ${P}-u ${YELLOW}<${NC}url${YELLOW}>${NC}"
      exit 1
    else
      SOCKS5=$ADDR:$PORT
      echo -e "\n${BLUE}[${LB}OK${BLUE}]${P} Default Address: ${WHITE}$ADDR${GREEN}:${WHITE}$PORT${NC}"
      curl -s --socks5-hostname $SOCKS5 "$url" && echo -e "\n${NC}" || echo -e "\n${RED}[${WHITE}X${RED}] Could not resolv: ${ORANGE}'$url'${NC}"
      exit 0
    fi

    shift
    break

    ;;

    -a)
    mode=2
    NEW_ADDR=$2
    url=$3

    if [[ -z $NEW_ADDR || -z $url ]]; then
      echo -e "\n${RED}[${WHITE}X${RED}] Missing url or address${NC}"
      echo -e "\n${RED}[${YELLOW}warn${RED}]${ORANGE} usage: ${LB}neptune ${P}-a${NC}<${BLUE}addr${NC}> <${BLUE}url${NC}>${NC}"
      exit 1
    else
      SOCKS5="$NEW_ADDR"
      curl --socks5-hostname $SOCKS5 "$url" && echo -e "\n${NC}" || echo -e "\n${RED}[${WHITE}X${RED}] Could not resolv: ${ORANGE}'$url'${NC}"
      exit 0
    fi

    shift
    break

    ;;

    -s)
    mode=3
    addr=$2
    DEMO="curl_out"

    if ! [ -f /etc/resolv.conf ]; then
      touch /etc/resolv.conf >/dev/null 2>&1
    fi

    if [ -z $addr ]; then
      echo -e "\n${RED}[${WHITE}X${RED}] Missing the address to set${NC}"
      echo -e "\n${RED}[${YELLOW}warn${RED}]${ORANGE} usage: ${LB}neptune ${BLUE}-s ${YELLOW}<${BLUE}addr${YELLOW}>${NC}"
      exit 1
    else

      chattr -i /etc/resolv.conf >/dev/null 2>&1
      rm /etc/resolv.conf >/dev/null 2>&1
      touch /etc/resolv.conf >/dev/null 2>&1

      echo "nameserver $addr" | tee /etc/resolv.conf >/dev/null 2>&1 && echo -e "\n${BLUE}[${LB}OK${BLUE}]${P} New dns address: ${GREEN}$addr${NC}" || echo -e "\n${RED}[${WHITE}X${RED}] Could not set dns address${NC}"

      read -e -p "\033[97mDo you want to test the addr (y/n)?\033[0m  " r "$r"

      if [ -z "$r" ]; then
          exit 0
      elif [ "$r" == "N|n" ]]; then
            exit 0
      elif [ "$r" == "Y|y" ]; then
            echo -e "\n${BLUE}[${WHITE}*${BLUE}]${WHITE} Looking for web portals..${NC}"

            sleep 1

            curl "$addr" | tee "$DEMO" >/dev/null 2>&1 && echo -e "\n${GREEN}[*] Discovered http/s web portal, check output: ${ORANGE}'$DEMO'${NC}" || echo -e "\n${RED}[x] Failed to check for http/s servers, check output: ${ORANGE}'$DEMO'${NC}"
      fi

            read -e -p "\033[97mShow curl output (y/n)?\033[0m  " r "$r"

            echo -e "\n"
            
            if [ "$r" == "y|Y" ]; then
                cat "$DEMO"
                echo -e "\n"
            fi

            sleep 1

            read -e -p "\033[97mMake a ping test (y/n)?\033[0m  " r "$r"

            [[ -z "$r" || "$r" == "N|n" ]] && exit 1

            sleep 1

            echo -e "\n${BLUE}[${WHITE}*${BLUE}]${WHITE} ICMP Test (ping)${NC}"

            read -e -p "\033[97mIPv4 or IPv6 (4/6/both)?\033[0m  " r "$r"

            read -e -p "\033[97mHow many packets to send, default: 5, (n/empty)\033[0m  " count "$count"

            [[ -z "$count" ]] && count=5

                  icmpv4(){
                  for c in "$count"; do
                      ping -4 -c 1 "$addr" >/dev/null 2>&1 && echo -e "\n${BLUE}[${WHITE}*${BLUE}]${YELLOW} Echo4 reply: "$c"${NC}" || echo -e "\n${RED}[*] Lost reply4: ${ORANGE}$c${NC}"
                  done
                  }

                  icmpv6(){
                  for c in "$count"; do
                      ping -4 -c 1 "$addr" >/dev/null 2>&1 && echo -e "\n${BLUE}[${WHITE}*${BLUE}]${YELLOW} Echo6 reply: "$c"${NC}" || echo -e "\n${RED}[*] Lost reply6: ${ORANGE}$c${NC}"
                  done
                  }

            elif [ "$r" == "4" ]; then
                  icmpv4
            elif [ "$r" == "6" ]; then
                  icmpv6
            elif [ "$r" == "both" ]; then
                  echo -e "\n${BLUE}[${WHITE}*${BLUE}]${WHITE} Perform ICMPv4${NC}"
                  icmpv4

                  sleep 1

                  echo -e "\n${BLUE}[${WHITE}*${BLUE}]${WHITE} Perform ICMPv6${NC}"
                  icmpv6
            fi

    fi

    shift
    break
    ;;

    -h)
    mode=4

    usage
    exit 1

    shift
    break

    ;;

  --* | -* | *)
    mode=4

    echo -e "\n${RED}[${WHITE}X${RED}] Invalid param: ${ORANGE}'$1'${NC}"
    echo -e "\n${RED}[${YELLOW}warn${RED}] Try: ${LB}'neptune -h'${NC}"
    exit 1

    shift
    break

    ;;

  esac
done

if [ -z "$mode" ]; then
  usage
  exit 1
fi
