#!/bin/bash

################################################################################################################
#                                                                                                              #
# SATURN - Tool for managing things like MAC changing or system interfaces easly                               #
# CODED BY: archnon@protonmail.com                                                                             #
#                                                                                                              #
################################################################################################################

####################################################################
# Copyright (c) 2026 archnon@protonmail.com. All Rights Reserved.  #
####################################################################

##### colors #####

RED="\e[1;31m"

GREEN="\e[1;32m"

BLUE="\e[1;34m"

P="\e[1;35m"

YELLOW="\e[1;33m"

ORANGE="\e[38;5;214m"

WHITE="\e[1;37m"

LB="\e[36m"

NC="\e[0m"

if ! (command -v ip >/dev/null 2>&1 && command -v macchanger >/dev/null 2>&1); then

  pkgs=(macchanger iproute2)

  if [[ $(command -v apt) ]]; then
    if ! apt install -y ${pkgs[@]}; then
      echo -e "\n${RED}[${WHITE}X${RED}] Install: ${ORANGE}'${pkgs[@]}'${NC}"
      exit 1
    fi
  elif [[ $(command -v pacman) ]]; then
    if ! pacman -Sy --noconfirm --needed --overwrite "*" ${pkgs[@]}; then
      echo -e "\n${RED}[${WHITE}X${RED}] Install: ${ORANGE}'${pkgs[@]}'${NC}"
      exit 1
    fi
  elif [[ $(command -v dnf) ]]; then
    if ! dnf install -y --allowerasing ${pkgs[@]}; then
      echo -e "\n${RED}[${WHITE}X${RED}] Install: ${ORANGE}'${pkgs[@]}'${NC}"
      exit 1
    fi
  elif [[ $(command -v yum) ]]; then
    if ! yum install -y ${pkgs[@]}; then
      echo -e "\n${RED}[${WHITE}X${RED}] Install: ${ORANGE}'${pkgs[@]}'${NC}"
      exit 1
    fi
  elif [[ $(command -v xbps-install) ]]; then
    if ! xbps-install -Sy -f -y "*" ${pkgs[@]}; then
      echo -e "\n${RED}[${WHITE}X${RED}] Install: ${ORANGE}'${pkgs[@]}'${NC}"
      exit 1
    fi
  elif [[ $(command -v zypper) ]]; then
    if ! zypper install ${pkgs[@]}; then
      echo -e "\n${RED}[${WHITE}X${RED}] Install: ${ORANGE}'${pkgs[@]}'${NC}"
      exit 1
    fi
  elif [[ $(command -v apk) ]]; then
    if ! apk add --no-cache ${pkgs[@]}; then
      echo -e "\n${RED}[${WHITE}X${RED}] Install: ${ORANGE}'${pkgs[@]}'${NC}"
      exit 1
    fi
  elif [[ $(command -v emerge) ]]; then
    if ! emerge -v --oneshot --keep-going ${pkgs[@]}; then
      echo -e "\n${RED}[${WHITE}X${RED}] Install: ${ORANGE}'${pkgs[@]}'${NC}"
      exit 1
    fi
  else
    echo -e "\n${RED}[${WHITE}X${RED}] Unsuported package manager, install: ${ORANGE}'${pkgs[@]}'${NC}"
    exit 1
  fi
fi

##### Banner #####

echo -e "${YELLOW}                                     ";
echo -e "${YELLOW}                                     ";
echo -e "${YELLOW} ▄▄▄▄  ▄▄▄ ▄▄▄▄▄▄ ▄▄ ▄▄ ▄▄▄▄  ▄▄  ▄▄ ";
echo -e "${YELLOW}███▄▄ ██▀██  ██   ██ ██ ██▄█▄ ███▄██ ";
echo -e "${YELLOW}▄▄██▀ ██▀██  ██   ▀███▀ ██ ██ ██ ▀██ ";
echo -e "${YELLOW}                                     ";

echo -e "\e[94m ╔══════════════════════════════════╗
 ║ \e[92mlazy tool for interfaces and MAC\e[94m ║
 ╚══════════════════════════════════╝\e[0m"
echo -e "\e[97m [ ᴅᴇᴠᴇʟᴏᴘᴇᴅ ʙʏ: \e[95m@strxint\e[97m ]\e[0m"

usage() {
  echo -e "\n${RED}[${YELLOW}warn${RED}]${ORANGE} usage: ${P}saturn ${NC}<${GREEN}COMMAND${NC}> ${NC}<${GREEN}OPTIONS${NC}>${NC}"
  echo -e "\n${BLUE}[${ORANGE}1${BLUE}] ${LB}change: ${WHITE}change MAC${NC}"
  echo -e "\n${BLUE}[${ORANGE}2${BLUE}] ${LB}enable: ${WHITE}enable change MAC on boot${NC}"
  echo -e "\n${BLUE}[${ORANGE}3${BLUE}] ${LB}disable: ${WHITE}disable ${GREEN}change MAC on boot${NC}"
  echo -e "\n${BLUE}[${ORANGE}4${BLUE}] ${LB}background ${NC}<${P}args${NC}>: ${WHITE}change MAC in bg${NC}"
  echo -e "\n${BLUE}[${ORANGE}5${BLUE}] ${LB}restore: ${WHITE}restore MAC${NC}"
  echo -e "\n${BLUE}[${ORANGE}6${BLUE}] ${LB}list: ${WHITE}list devices${NC}"
  echo -e "\n${BLUE}[${ORANGE}7${BLUE}] ${LB}help: ${WHITE}print manual${NC}"
}

change() {
  ip link set $device down >/dev/null 2>&1

  macchanger -r -b $device >/dev/null 2>&1

  ip link set $device up >/dev/null 2>&1
}

restore() {
  ip link set $device down >/dev/null 2>&1

  macchanger -p $device >/dev/null 2>&1

  ip link set $device up >/dev/null 2>&1
}

createsv() {

  label=saturn

  if [ ! -f /etc/systemd/system/$label.service ] && command -v systemctl >/dev/null 2>&1; then
    touch /etc/systemd/system/$label.service

    echo -e "\n[Unit]\nDescription=$label $device\n[Service]\nType=forking\nExecStart=$label change $device\nRemainAfterExit=yes\nUser=root\n[Install]\nWantedBy=multi-user.target" >>/etc/systemd/system/$label.service

  fi

  if [ ! -f /etc/sv/$label/run ] && command -v runit >/dev/null 2>&1; then
    mkdir -p /etc/sv/$label/
    touch /etc/sv/$label/run

    echo -e "#!/bin/sh\nexec $label change $device" >>/etc/sv/$label/run
    chmod +x /etc/sv/$label/run
  fi

  if [ ! -f /etc/init.d/$label ] && command -v rc-service >/dev/null 2>&1; then
    touch /etc/init.d/$label

    echo "#!/sbin/openrc-run\nname=$label $device\ncommand="$label"\ncommand_args="change $device"\ncommand_background=true\npidfile="/run/${RC_SVCNAME}.pid"\ndepend() {\n    need net\n}" >>/etc/init.d/$label

    chmod +x /etc/init.d/$label >/dev/null 2>&1
  fi
}

enable() {

  if [ -f /etc/systemd/system/$label.service ] && command -v systemctl >/dev/null 2>&1; then

    if systemctl is-enabled $label >/dev/null 2>&1; then
      echo -e "\n${BLUE}[${LB}OK${BLUE}]${P} Program will run on boot${NC}"
      exit 1
    else
      systemctl enable $label >/dev/null 2>&1 && echo -e "\n${BLUE}[${LB}OK${BLUE}]${P} Program will run on boot${NC}" || echo -e "\n${RED}[${WHITE}X${RED}] Program wont run on boot due to an unexcepted error${NC}"
    fi
  fi

  if [ -f /etc/sv/$label/run ] && command -v runit >/dev/null 2>&1; then

    if [ -d /run/runit/service ]; then
      RSDIR=/run/runit/service
    elif [ -d /etc/service ]; then
      RSDIR=/etc/service
    elif [ -d /var/run/service ]; then
      RSDIR=/var/run/service
    fi

    if ls -l $RSDIR/$label/ >/dev/null 2>&1; then
      echo -e "\n${BLUE}[${LB}OK${BLUE}]${P} Program will run on boot${NC}"
      exit 1
    else
      ln -s /etc/sv/$label $RSDIR >/dev/null 2>&1 && echo -e "\n${BLUE}[${LB}OK${BLUE}]${P} Program will run on boot${NC}" || echo -e "\n${RED}[${WHITE}X${RED}] Program wont run on boot due to an unexcepted error${NC}"
    fi
  fi

  if [ -f /etc/init.d/$label ] && command -v rc-update >/dev/null 2>&1; then

    if rc-update | grep -IE "$label" >/dev/null 2>&1; then
      echo -e "\n${BLUE}[${LB}OK${BLUE}]${P} Program will run on boot${NC}"
      exit 1
    else
      rc-update add $label default >/dev/null 2>&1 && echo -e "\n${BLUE}[${LB}OK${BLUE}]${P} Program will run on boot${NC}" || echo -e "\n${RED}[${WHITE}X${RED}] Program wont run on boot due to an unexcepted error${NC}"
    fi
  fi
}

disable() {
  if [ -f /etc/systemd/system/$label.service ] && command -v systemctl >/dev/null 2>&1; then

    if ! systemctl is-enabled $label >/dev/null 2>&1; then
      echo -e "\n${BLUE}[${LB}OK${BLUE}]${P} Program wont run on boot${NC}"
      exit 0
    else
      systemctl disable $label >/dev/null 2>&1 && echo -e "\n${BLUE}[${LB}OK${BLUE}]${P} Program wont run on boot${NC}" || echo -e "\n${RED}[${WHITE}X${RED}] Program can still run on boot due to an unexcepted error${NC}"
      exit 1
    fi
  fi

  if [ -f /etc/sv/$label/run ] && command -v runit >/dev/null 2>&1; then

    if [ -d /run/runit/service ]; then
      RSDIR=/run/runit/service

    elif [ -d /etc/service ]; then
      RSDIR=/etc/service

    elif [ -d /var/run/service ]; then
      RSDIR=/var/run/service
    fi

    if ! ls -l $RSDIR/$label/ >/dev/null 2>&1; then
      echo -e "\n${BLUE}[${LB}OK${BLUE}]${P} Program wont run on boot${NC}"
      exit 0
    else
      rm -rf $RSDIR/$label >/dev/null 2>&1 && echo -e "\n${BLUE}[${LB}OK${BLUE}]${P} Program wont run on boot${NC}" || echo -e "\n${RED}[${WHITE}X${RED}] Program can still run on boot due to an unexcepted error${NC}"
      exit 1
    fi
  fi

  if [ -f /etc/init.d/$label ] && command -v rc-service >/dev/null 2>&1; then

    if ! rc-update | grep -IE "$label" >/dev/null 2>&1; then
      echo -e "\n${BLUE}[${LB}OK${BLUE}]${P} Program wont run on boot${NC}"
      exit 0
    else
      rc-update del $label default >/dev/null 2>&1 && echo -e "\n${BLUE}[${LB}OK${BLUE}]${P} Program wont run on boot${NC}" || echo -e "\n${RED}[${WHITE}X${RED}] Program can still run on boot due to an unexcepted error${NC}"
      exit 1
    fi
  fi
}

dlist() {
  if pgrep -x mars >/dev/null 2>&1; then
    echo -e "\n${BLUE}[${LB}OK${BLUE}]${P} Active PID: ${NC}"
    pgrep -a mars
    echo -e "\n${RED}[${YELLOW}warn${RED}] Kill: ${RED}pkill -9 mars${NC}"
  fi
}

while [ $# -gt 0 ]; do
  case $1 in

  change)
    mode=1
    device=$2

    if [ $EUID -ne 0 ]; then
      echo -e "\n${RED}[${WHITE}X${RED}] Run as root${NC}"
      exit 1
    fi

    if [ -z $device ]; then
      echo -e "\n${RED}[${WHITE}X${RED}] Missing a device${NC}"
      exit 1
    fi

    if ! macchanger -s "$device" >/dev/null 2>&1; then
      echo -e "\n${RED}[${WHITE}X${RED}] No such device: ${ORANGE}'$device'${NC}"
      exit 1
    fi

    change && echo -e "\n${BLUE}[${LB}OK${BLUE}]${P} $(macchanger -s $device | grep Current)${NC}" || echo -e "\n${RED}[${WHITE}X${RED}] no new MAC${NC}"
    exit 1

    shift
    break

    ;;

  enable)
    mode=2
    device=$2

    if [ $EUID -ne 0 ]; then
      echo -e "\n${RED}[${WHITE}X${RED}] Run as root${NC}"
      exit 1
    fi

    if [ -z $device ]; then
      echo -e "\n${RED}[${WHITE}X${RED}] Missing a device${NC}"
      exit 1
    fi

    if ! macchanger -s $device >/dev/null 2>&1; then
      echo -e "\n${RED}[${WHITE}X${RED}] No such device: ${ORANGE}'$device'${NC}"
      exit 1
    fi

    createsv

    enable

    exit 0

    shift
    break

    ;;

  disable)
    mode=3
    device=$3

    if [ $EUID -ne 0 ]; then
      echo -e "\n${RED}[${WHITE}X${RED}] Run as root${NC}"
      exit 1
    fi

    createsv

    disable

    exit 0

    shift
    break

    ;;

  background)
    mode=4
    dev=$2
    sec=$3

    if [ $EUID -ne 0 ]; then
      echo -e "\n${RED}[${WHITE}X${RED}] Run as root${NC}"
      exit 1
    fi

    if [[ -z "$dev" || -z "$sec" ]]; then
      echo -e "\n${RED}[${WHITE}X${RED}] usage: saturn background ${NC}<${P}device> <seconds>${NC}"
      exit 1
    fi

    if ! macchanger -s $device >/dev/null 2>&1; then
      echo -e "\n${RED}[${WHITE}X${RED}] No such device: ${ORANGE}'$device'${NC}"
      exit 1
    fi

    if ! command -v mars >>/dev/null 2>&1; then
      echo -e "\n${RED}[${WHITE}X${RED}] Missing background script: ${ORANGE}'mars'${NC}"
      exit 1
    else
      mars $device $sec && echo -e "\n${BLUE}[${LB}OK${BLUE}]${P} launch background pid${NC}" || echo -e "\n${RED}[${WHITE}X${RED}] launch background pid${NC}"
      dlist
      exit 0
    fi

    shift
    break

    ;;

  restore)
    mode=5
    device=$2

    if [ $EUID -ne 0 ]; then
      echo -e "\n${RED}[${WHITE}X${RED}] Run as root${NC}"
      exit 1
    fi

    if [ -z $device ]; then
      usage
      echo -e "\n${RED}[${WHITE}X${RED}] Missing device${NC}"
      exit 1
    fi

    if ! macchanger -s "$device" >/dev/null 2>&1; then
      echo -e "\n${RED}[${WHITE}X${RED}] No such device: ${ORANGE}'$device'${NC}"
      exit 1
    fi

    restore && echo -e "\n${BLUE}[${LB}OK${BLUE}]${P} $(macchanger -s $device | grep Current)${NC}" || echo -e "\n${RED}[${WHITE}X${RED}] restore MAC${NC}"
    exit 0

    shift
    break

    ;;

  list)
    mode=6

    if ! ip link >/dev/null 2>&1; then
      echo -e "\n${RED}[${WHITE}X${RED}] show devices${NC}"
      exit 1
    else
      echo -n -e "\n"
      ip link
      exit 0
    fi

    shift
    break

    ;;

  help)
    mode=6
    usage
    exit 1

    shift
    break

    ;;

  --* | -* | *)
    mode=7

    usage
    exit 1

    shift
    break

    ;;

  esac
done

if [ -z $mode ]; then
  usage
  exit 1
fi
